### ISSUE TITLE
Filepicker modal only displayed after initial page load

### ISSUE THREAD

**Issue by Strosch** [guido4000/loadpicker#3]
Hi!

So I just found a bug.
When I call filepicker.pick() for the first time in a template everything works fine. Also closing the modal and clicking the button again works fine (modal is displayed again). When I click on a link inside my meteor app to get to another page (of course via html5 pushstate like on every meteor page, no standard a links with a real page refresh) and then go back to the page with the filepicker stuff in it, the button does not do anything anymore. The filepicker modal or anything is NOT displayed.

I hope you understand the bug. Any ideas? :)

best regards
Patrick

**Comment by guido4000** [comment]
Did you try both integration options? template.yourTemplate.created / template.yourTemplate.rendered

**Comment by pradeepmogi** [comment]
I'am also facing same problem. any suggestions please replay

**Comment by davidwoody** [comment]
I ran into the same thing, and I followed the advice here:

https://groups.google.com/forum/#!topic/meteor-talk/_OEZLder_54 

Summary:
1) mrt add filepicker 
2) Put this into a Template.name.created: filepicker.setKey("YOUR_API_KEY_HERE");
3) Follow the web documentation here: https://developers.inkfilepicker.com/docs/
